project_name: skpr-api
version: 2

builds:
  - id: skpr-apiserver-mock
    main: ./cmd/apiserver-mock
    binary: skpr-apiserver-mock
    ldflags:
      - -extldflags '-static'
    env:
      - CGO_ENABLED=0
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]

dockers_v2:
  - id: skpr-apiserver-mock
    dockerfile: dockerfiles/apiserver-mock/Dockerfile
    ids:
      - skpr-apiserver-mock
    images:
      - ghcr.io/skpr/api
    tags:
      - "{{ .Major }}.{{ .Minor }}"
      - "latest"
    sbom: false
    flags:
      - "--pull"
    platforms:
      - linux/amd64
      - linux/arm64

changelog:
  use: github-native
