project_name: skpr-api
version: 2

builds:
  - id: skpr-apiserver-mock
    main: ./cmd/apiserver-mock
    binary: skpr-apiserver-mock
    ldflags:
      - -extldflags '-static'
    env:
      - CGO_ENABLED=0
    goos: [ linux ]
    goarch: [ amd64, arm64 ]

dockers:
  - dockerfile: dockerfiles/apiserver-mock/Dockerfile
    image_templates:
      - "ghcr.io/skpr/api:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/skpr/api:latest-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    use: buildx
  - dockerfile: dockerfiles/apiserver-mock/Dockerfile
    image_templates:
      - "ghcr.io/skpr/api:{{ .Major }}.{{ .Minor }}-arm64"
      - "ghcr.io/skpr/api:latest-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    use: buildx
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/skpr/api:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/skpr/api:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/skpr/api:{{ .Major }}.{{ .Minor }}-arm64"
  - name_template: "ghcr.io/skpr/api:latest"
    image_templates:
      - "ghcr.io/skpr/api:latest-amd64"
      - "ghcr.io/skpr/api:latest-arm64"

release:
  draft: true
