project_name: skpr-mock-cluster
version: 2

builds:
  - id: skpr-apiserver-mock
    main: ./cmd/apiserver-mock
    binary: skpr-apiserver-mock
    ldflags:
      - -extldflags '-static'
    env:
      - CGO_ENABLED=0
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]

dockers:
  - dockerfile: dockerfiles/apiserver-mock/Dockerfile
    image_templates:
      - "ghcr.io/skpr/api:{{ .Version }}-amd64"
      - "ghcr.io/skpr/api:latest-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
    use: buildx
  - dockerfile: dockerfiles/apiserver-mock/Dockerfile
    image_templates:
      - "ghcr.io/skpr/api:{{ .Version }}-arm64"
      - "ghcr.io/skpr/api:latest-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
    use: buildx

docker_manifests:
  - name_template: "ghcr.io/skpr/api:{{ .Version }}"
    image_templates:
      - "ghcr.io/skpr/api:{{ .Version }}-amd64"
      - "ghcr.io/skpr/api:{{ .Version }}-arm64"
