// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: compass.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CompassClient is the client API for Compass service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CompassClient interface {
	// Stream Compass traces from a specific environment.
	StreamTraces(ctx context.Context, in *StreamTracesRequest, opts ...grpc.CallOption) (Compass_StreamTracesClient, error)
}

type compassClient struct {
	cc grpc.ClientConnInterface
}

func NewCompassClient(cc grpc.ClientConnInterface) CompassClient {
	return &compassClient{cc}
}

func (c *compassClient) StreamTraces(ctx context.Context, in *StreamTracesRequest, opts ...grpc.CallOption) (Compass_StreamTracesClient, error) {
	stream, err := c.cc.NewStream(ctx, &Compass_ServiceDesc.Streams[0], "/workflow.compass/StreamTraces", opts...)
	if err != nil {
		return nil, err
	}
	x := &compassStreamTracesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Compass_StreamTracesClient interface {
	Recv() (*StreamTracesResponse, error)
	grpc.ClientStream
}

type compassStreamTracesClient struct {
	grpc.ClientStream
}

func (x *compassStreamTracesClient) Recv() (*StreamTracesResponse, error) {
	m := new(StreamTracesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CompassServer is the server API for Compass service.
// All implementations must embed UnimplementedCompassServer
// for forward compatibility
type CompassServer interface {
	// Stream Compass traces from a specific environment.
	StreamTraces(*StreamTracesRequest, Compass_StreamTracesServer) error
	mustEmbedUnimplementedCompassServer()
}

// UnimplementedCompassServer must be embedded to have forward compatible implementations.
type UnimplementedCompassServer struct {
}

func (UnimplementedCompassServer) StreamTraces(*StreamTracesRequest, Compass_StreamTracesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTraces not implemented")
}
func (UnimplementedCompassServer) mustEmbedUnimplementedCompassServer() {}

// UnsafeCompassServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CompassServer will
// result in compilation errors.
type UnsafeCompassServer interface {
	mustEmbedUnimplementedCompassServer()
}

func RegisterCompassServer(s grpc.ServiceRegistrar, srv CompassServer) {
	s.RegisterService(&Compass_ServiceDesc, srv)
}

func _Compass_StreamTraces_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTracesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CompassServer).StreamTraces(m, &compassStreamTracesServer{stream})
}

type Compass_StreamTracesServer interface {
	Send(*StreamTracesResponse) error
	grpc.ServerStream
}

type compassStreamTracesServer struct {
	grpc.ServerStream
}

func (x *compassStreamTracesServer) Send(m *StreamTracesResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Compass_ServiceDesc is the grpc.ServiceDesc for Compass service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Compass_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workflow.compass",
	HandlerType: (*CompassServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTraces",
			Handler:       _Compass_StreamTraces_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "compass.proto",
}
