// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: metrics.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsClient interface {
	// A list of all available metrics.
	AvailableMetrics(ctx context.Context, in *AvailableMetricsRequest, opts ...grpc.CallOption) (*AvailableMetricsResponse, error)
	// Metric values for a given absolute range.
	AbsoluteRange(ctx context.Context, in *AbsoluteRangeRequest, opts ...grpc.CallOption) (*AbsoluteRangeResponse, error)
}

type metricsClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsClient(cc grpc.ClientConnInterface) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) AvailableMetrics(ctx context.Context, in *AvailableMetricsRequest, opts ...grpc.CallOption) (*AvailableMetricsResponse, error) {
	out := new(AvailableMetricsResponse)
	err := c.cc.Invoke(ctx, "/workflow.metrics/AvailableMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) AbsoluteRange(ctx context.Context, in *AbsoluteRangeRequest, opts ...grpc.CallOption) (*AbsoluteRangeResponse, error) {
	out := new(AbsoluteRangeResponse)
	err := c.cc.Invoke(ctx, "/workflow.metrics/AbsoluteRange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
// All implementations must embed UnimplementedMetricsServer
// for forward compatibility
type MetricsServer interface {
	// A list of all available metrics.
	AvailableMetrics(context.Context, *AvailableMetricsRequest) (*AvailableMetricsResponse, error)
	// Metric values for a given absolute range.
	AbsoluteRange(context.Context, *AbsoluteRangeRequest) (*AbsoluteRangeResponse, error)
	mustEmbedUnimplementedMetricsServer()
}

// UnimplementedMetricsServer must be embedded to have forward compatible implementations.
type UnimplementedMetricsServer struct {
}

func (UnimplementedMetricsServer) AvailableMetrics(context.Context, *AvailableMetricsRequest) (*AvailableMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AvailableMetrics not implemented")
}
func (UnimplementedMetricsServer) AbsoluteRange(context.Context, *AbsoluteRangeRequest) (*AbsoluteRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbsoluteRange not implemented")
}
func (UnimplementedMetricsServer) mustEmbedUnimplementedMetricsServer() {}

// UnsafeMetricsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServer will
// result in compilation errors.
type UnsafeMetricsServer interface {
	mustEmbedUnimplementedMetricsServer()
}

func RegisterMetricsServer(s grpc.ServiceRegistrar, srv MetricsServer) {
	s.RegisterService(&Metrics_ServiceDesc, srv)
}

func _Metrics_AvailableMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AvailableMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).AvailableMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflow.metrics/AvailableMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).AvailableMetrics(ctx, req.(*AvailableMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_AbsoluteRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbsoluteRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).AbsoluteRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/workflow.metrics/AbsoluteRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).AbsoluteRange(ctx, req.(*AbsoluteRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Metrics_ServiceDesc is the grpc.ServiceDesc for Metrics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metrics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workflow.metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AvailableMetrics",
			Handler:    _Metrics_AvailableMetrics_Handler,
		},
		{
			MethodName: "AbsoluteRange",
			Handler:    _Metrics_AbsoluteRange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metrics.proto",
}
