//* Service responsible for coordinating environment restores

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: restore.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RestoreStatus_Phase int32

const (
	RestoreStatus_InProgress RestoreStatus_Phase = 0 // Default value
	RestoreStatus_Completed  RestoreStatus_Phase = 1 // The backup completed
	RestoreStatus_Failed     RestoreStatus_Phase = 2 // The backup failed
	RestoreStatus_Unknown    RestoreStatus_Phase = 3 // Backup status is unknown
)

// Enum value maps for RestoreStatus_Phase.
var (
	RestoreStatus_Phase_name = map[int32]string{
		0: "InProgress",
		1: "Completed",
		2: "Failed",
		3: "Unknown",
	}
	RestoreStatus_Phase_value = map[string]int32{
		"InProgress": 0,
		"Completed":  1,
		"Failed":     2,
		"Unknown":    3,
	}
)

func (x RestoreStatus_Phase) Enum() *RestoreStatus_Phase {
	p := new(RestoreStatus_Phase)
	*p = x
	return p
}

func (x RestoreStatus_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RestoreStatus_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_restore_proto_enumTypes[0].Descriptor()
}

func (RestoreStatus_Phase) Type() protoreflect.EnumType {
	return &file_restore_proto_enumTypes[0]
}

func (x RestoreStatus_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RestoreStatus_Phase.Descriptor instead.
func (RestoreStatus_Phase) EnumDescriptor() ([]byte, []int) {
	return file_restore_proto_rawDescGZIP(), []int{6, 0}
}

// *
// Create a restore request
type RestoreCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Environment string `protobuf:"bytes,1,opt,name=Environment,proto3" json:"Environment,omitempty"` // Environment name
	Backup      string `protobuf:"bytes,2,opt,name=Backup,proto3" json:"Backup,omitempty"`           // Backup identifier
}

func (x *RestoreCreateRequest) Reset() {
	*x = RestoreCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreCreateRequest) ProtoMessage() {}

func (x *RestoreCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreCreateRequest.ProtoReflect.Descriptor instead.
func (*RestoreCreateRequest) Descriptor() ([]byte, []int) {
	return file_restore_proto_rawDescGZIP(), []int{0}
}

func (x *RestoreCreateRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *RestoreCreateRequest) GetBackup() string {
	if x != nil {
		return x.Backup
	}
	return ""
}

// *
// Returns an ID if the restore creation was successful
type RestoreCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"` // ID of the restore
}

func (x *RestoreCreateResponse) Reset() {
	*x = RestoreCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restore_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreCreateResponse) ProtoMessage() {}

func (x *RestoreCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restore_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreCreateResponse.ProtoReflect.Descriptor instead.
func (*RestoreCreateResponse) Descriptor() ([]byte, []int) {
	return file_restore_proto_rawDescGZIP(), []int{1}
}

func (x *RestoreCreateResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

// *
// Get the latest information for a restore
type RestoreGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"` // ID of the restore
}

func (x *RestoreGetRequest) Reset() {
	*x = RestoreGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restore_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreGetRequest) ProtoMessage() {}

func (x *RestoreGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restore_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreGetRequest.ProtoReflect.Descriptor instead.
func (*RestoreGetRequest) Descriptor() ([]byte, []int) {
	return file_restore_proto_rawDescGZIP(), []int{2}
}

func (x *RestoreGetRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

// *
// Returns restore information
type RestoreGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Restore *RestoreStatus `protobuf:"bytes,1,opt,name=Restore,proto3" json:"Restore,omitempty"`
}

func (x *RestoreGetResponse) Reset() {
	*x = RestoreGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restore_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreGetResponse) ProtoMessage() {}

func (x *RestoreGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restore_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreGetResponse.ProtoReflect.Descriptor instead.
func (*RestoreGetResponse) Descriptor() ([]byte, []int) {
	return file_restore_proto_rawDescGZIP(), []int{3}
}

func (x *RestoreGetResponse) GetRestore() *RestoreStatus {
	if x != nil {
		return x.Restore
	}
	return nil
}

// *
// List restores for an environment
type RestoreListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Environment string `protobuf:"bytes,1,opt,name=Environment,proto3" json:"Environment,omitempty"` // Environment name
}

func (x *RestoreListRequest) Reset() {
	*x = RestoreListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restore_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreListRequest) ProtoMessage() {}

func (x *RestoreListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restore_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreListRequest.ProtoReflect.Descriptor instead.
func (*RestoreListRequest) Descriptor() ([]byte, []int) {
	return file_restore_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreListRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

// *
// Returns a list of restores
type RestoreListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*RestoreStatus `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *RestoreListResponse) Reset() {
	*x = RestoreListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restore_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreListResponse) ProtoMessage() {}

func (x *RestoreListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restore_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreListResponse.ProtoReflect.Descriptor instead.
func (*RestoreListResponse) Descriptor() ([]byte, []int) {
	return file_restore_proto_rawDescGZIP(), []int{5}
}

func (x *RestoreListResponse) GetList() []*RestoreStatus {
	if x != nil {
		return x.List
	}
	return nil
}

// *
// Restore status information
type RestoreStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string              `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`                                      // Name of the restore
	Backup         string              `protobuf:"bytes,2,opt,name=Backup,proto3" json:"Backup,omitempty"`                                  // Backup used for the restore
	Phase          RestoreStatus_Phase `protobuf:"varint,3,opt,name=phase,proto3,enum=workflow.RestoreStatus_Phase" json:"phase,omitempty"` // Phase of the restore
	StartTime      string              `protobuf:"bytes,4,opt,name=StartTime,proto3" json:"StartTime,omitempty"`                            // When the restore was started
	CompletionTime string              `protobuf:"bytes,5,opt,name=CompletionTime,proto3" json:"CompletionTime,omitempty"`                  // When the restore was completed
	Duration       string              `protobuf:"bytes,6,opt,name=Duration,proto3" json:"Duration,omitempty"`                              // How long the restore took to complete
	Databases      []string            `protobuf:"bytes,7,rep,name=Databases,proto3" json:"Databases,omitempty"`                            // Databases associated with the restore
	Volumes        []string            `protobuf:"bytes,8,rep,name=Volumes,proto3" json:"Volumes,omitempty"`                                // Volumes associated with the restore
}

func (x *RestoreStatus) Reset() {
	*x = RestoreStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_restore_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RestoreStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreStatus) ProtoMessage() {}

func (x *RestoreStatus) ProtoReflect() protoreflect.Message {
	mi := &file_restore_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreStatus.ProtoReflect.Descriptor instead.
func (*RestoreStatus) Descriptor() ([]byte, []int) {
	return file_restore_proto_rawDescGZIP(), []int{6}
}

func (x *RestoreStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestoreStatus) GetBackup() string {
	if x != nil {
		return x.Backup
	}
	return ""
}

func (x *RestoreStatus) GetPhase() RestoreStatus_Phase {
	if x != nil {
		return x.Phase
	}
	return RestoreStatus_InProgress
}

func (x *RestoreStatus) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *RestoreStatus) GetCompletionTime() string {
	if x != nil {
		return x.CompletionTime
	}
	return ""
}

func (x *RestoreStatus) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *RestoreStatus) GetDatabases() []string {
	if x != nil {
		return x.Databases
	}
	return nil
}

func (x *RestoreStatus) GetVolumes() []string {
	if x != nil {
		return x.Volumes
	}
	return nil
}

var File_restore_proto protoreflect.FileDescriptor

var file_restore_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x22, 0x50, 0x0a, 0x14, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x22, 0x27, 0x0a, 0x15, 0x52,
	0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x23, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x47, 0x0a, 0x12, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x31, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x07, 0x52, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x22, 0x36, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x45,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x42, 0x0a, 0x13, 0x52, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2b, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xcb,
	0x02, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x33, 0x0a, 0x05,
	0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x73,
	0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x18, 0x08, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x22, 0x3f, 0x0a, 0x05, 0x50,
	0x68, 0x61, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x03, 0x32, 0xe1, 0x01, 0x0a,
	0x07, 0x72, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x4b, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x1e, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x52, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x52, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1c, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_restore_proto_rawDescOnce sync.Once
	file_restore_proto_rawDescData = file_restore_proto_rawDesc
)

func file_restore_proto_rawDescGZIP() []byte {
	file_restore_proto_rawDescOnce.Do(func() {
		file_restore_proto_rawDescData = protoimpl.X.CompressGZIP(file_restore_proto_rawDescData)
	})
	return file_restore_proto_rawDescData
}

var file_restore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_restore_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_restore_proto_goTypes = []interface{}{
	(RestoreStatus_Phase)(0),      // 0: workflow.RestoreStatus.Phase
	(*RestoreCreateRequest)(nil),  // 1: workflow.RestoreCreateRequest
	(*RestoreCreateResponse)(nil), // 2: workflow.RestoreCreateResponse
	(*RestoreGetRequest)(nil),     // 3: workflow.RestoreGetRequest
	(*RestoreGetResponse)(nil),    // 4: workflow.RestoreGetResponse
	(*RestoreListRequest)(nil),    // 5: workflow.RestoreListRequest
	(*RestoreListResponse)(nil),   // 6: workflow.RestoreListResponse
	(*RestoreStatus)(nil),         // 7: workflow.RestoreStatus
}
var file_restore_proto_depIdxs = []int32{
	7, // 0: workflow.RestoreGetResponse.Restore:type_name -> workflow.RestoreStatus
	7, // 1: workflow.RestoreListResponse.List:type_name -> workflow.RestoreStatus
	0, // 2: workflow.RestoreStatus.phase:type_name -> workflow.RestoreStatus.Phase
	1, // 3: workflow.restore.Create:input_type -> workflow.RestoreCreateRequest
	3, // 4: workflow.restore.Get:input_type -> workflow.RestoreGetRequest
	5, // 5: workflow.restore.List:input_type -> workflow.RestoreListRequest
	2, // 6: workflow.restore.Create:output_type -> workflow.RestoreCreateResponse
	4, // 7: workflow.restore.Get:output_type -> workflow.RestoreGetResponse
	6, // 8: workflow.restore.List:output_type -> workflow.RestoreListResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_restore_proto_init() }
func file_restore_proto_init() {
	if File_restore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_restore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restore_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restore_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restore_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restore_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restore_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_restore_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RestoreStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_restore_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restore_proto_goTypes,
		DependencyIndexes: file_restore_proto_depIdxs,
		EnumInfos:         file_restore_proto_enumTypes,
		MessageInfos:      file_restore_proto_msgTypes,
	}.Build()
	File_restore_proto = out.File
	file_restore_proto_rawDesc = nil
	file_restore_proto_goTypes = nil
	file_restore_proto_depIdxs = nil
}
