//* Service responsible for coordinating project tags

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: tags.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// List a projects tags
type TagListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TagListRequest) Reset() {
	*x = TagListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tags_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListRequest) ProtoMessage() {}

func (x *TagListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tags_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListRequest.ProtoReflect.Descriptor instead.
func (*TagListRequest) Descriptor() ([]byte, []int) {
	return file_tags_proto_rawDescGZIP(), []int{0}
}

// *
// Returns a list of tags for a project
type TagListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags []string `protobuf:"bytes,1,rep,name=Tags,proto3" json:"Tags,omitempty"` // Tags associated with a project
}

func (x *TagListResponse) Reset() {
	*x = TagListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tags_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListResponse) ProtoMessage() {}

func (x *TagListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tags_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListResponse.ProtoReflect.Descriptor instead.
func (*TagListResponse) Descriptor() ([]byte, []int) {
	return file_tags_proto_rawDescGZIP(), []int{1}
}

func (x *TagListResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// *
// Add a tag to a project
type TagAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag string `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"` // Tag that we want to add to the project
}

func (x *TagAddRequest) Reset() {
	*x = TagAddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tags_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagAddRequest) ProtoMessage() {}

func (x *TagAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tags_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagAddRequest.ProtoReflect.Descriptor instead.
func (*TagAddRequest) Descriptor() ([]byte, []int) {
	return file_tags_proto_rawDescGZIP(), []int{2}
}

func (x *TagAddRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// *
// Returns the status of a project tag addition
type TagAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TagAddResponse) Reset() {
	*x = TagAddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tags_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagAddResponse) ProtoMessage() {}

func (x *TagAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tags_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagAddResponse.ProtoReflect.Descriptor instead.
func (*TagAddResponse) Descriptor() ([]byte, []int) {
	return file_tags_proto_rawDescGZIP(), []int{3}
}

// *
// Delete a projects tag
type TagDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag string `protobuf:"bytes,1,opt,name=Tag,proto3" json:"Tag,omitempty"` // Tag that we want to delete from the project
}

func (x *TagDeleteRequest) Reset() {
	*x = TagDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tags_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagDeleteRequest) ProtoMessage() {}

func (x *TagDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tags_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagDeleteRequest.ProtoReflect.Descriptor instead.
func (*TagDeleteRequest) Descriptor() ([]byte, []int) {
	return file_tags_proto_rawDescGZIP(), []int{4}
}

func (x *TagDeleteRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// *
// Returns the status of a project tag deletion
type TagDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TagDeleteResponse) Reset() {
	*x = TagDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tags_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagDeleteResponse) ProtoMessage() {}

func (x *TagDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tags_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagDeleteResponse.ProtoReflect.Descriptor instead.
func (*TagDeleteResponse) Descriptor() ([]byte, []int) {
	return file_tags_proto_rawDescGZIP(), []int{5}
}

var File_tags_proto protoreflect.FileDescriptor

var file_tags_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x74, 0x61, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x77, 0x6f,
	0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x22, 0x10, 0x0a, 0x0e, 0x54, 0x61, 0x67, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x0f, 0x54, 0x61, 0x67, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x54, 0x61, 0x67, 0x73, 0x22,
	0x21, 0x0a, 0x0d, 0x54, 0x61, 0x67, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54,
	0x61, 0x67, 0x22, 0x10, 0x0a, 0x0e, 0x54, 0x61, 0x67, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x0a, 0x10, 0x54, 0x61, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x54, 0x61, 0x67, 0x22, 0x13, 0x0a, 0x11, 0x54, 0x61,
	0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0xc5, 0x01, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x12, 0x3d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x18, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x54, 0x61, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x54, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x17, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x54, 0x61, 0x67, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x2e, 0x54, 0x61, 0x67, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x43, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x54, 0x61, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x2e, 0x54, 0x61, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tags_proto_rawDescOnce sync.Once
	file_tags_proto_rawDescData = file_tags_proto_rawDesc
)

func file_tags_proto_rawDescGZIP() []byte {
	file_tags_proto_rawDescOnce.Do(func() {
		file_tags_proto_rawDescData = protoimpl.X.CompressGZIP(file_tags_proto_rawDescData)
	})
	return file_tags_proto_rawDescData
}

var file_tags_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tags_proto_goTypes = []interface{}{
	(*TagListRequest)(nil),    // 0: workflow.TagListRequest
	(*TagListResponse)(nil),   // 1: workflow.TagListResponse
	(*TagAddRequest)(nil),     // 2: workflow.TagAddRequest
	(*TagAddResponse)(nil),    // 3: workflow.TagAddResponse
	(*TagDeleteRequest)(nil),  // 4: workflow.TagDeleteRequest
	(*TagDeleteResponse)(nil), // 5: workflow.TagDeleteResponse
}
var file_tags_proto_depIdxs = []int32{
	0, // 0: workflow.tag.List:input_type -> workflow.TagListRequest
	2, // 1: workflow.tag.Add:input_type -> workflow.TagAddRequest
	4, // 2: workflow.tag.Delete:input_type -> workflow.TagDeleteRequest
	1, // 3: workflow.tag.List:output_type -> workflow.TagListResponse
	3, // 4: workflow.tag.Add:output_type -> workflow.TagAddResponse
	5, // 5: workflow.tag.Delete:output_type -> workflow.TagDeleteResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tags_proto_init() }
func file_tags_proto_init() {
	if File_tags_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tags_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tags_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tags_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagAddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tags_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagAddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tags_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tags_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tags_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tags_proto_goTypes,
		DependencyIndexes: file_tags_proto_depIdxs,
		MessageInfos:      file_tags_proto_msgTypes,
	}.Build()
	File_tags_proto = out.File
	file_tags_proto_rawDesc = nil
	file_tags_proto_goTypes = nil
	file_tags_proto_depIdxs = nil
}
