// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: trace.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TraceClient is the client API for Trace service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TraceClient interface {
	// Stream Compass traces from a specific environment.
	StreamTraces(ctx context.Context, in *StreamTracesRequest, opts ...grpc.CallOption) (Trace_StreamTracesClient, error)
}

type traceClient struct {
	cc grpc.ClientConnInterface
}

func NewTraceClient(cc grpc.ClientConnInterface) TraceClient {
	return &traceClient{cc}
}

func (c *traceClient) StreamTraces(ctx context.Context, in *StreamTracesRequest, opts ...grpc.CallOption) (Trace_StreamTracesClient, error) {
	stream, err := c.cc.NewStream(ctx, &Trace_ServiceDesc.Streams[0], "/workflow.trace/StreamTraces", opts...)
	if err != nil {
		return nil, err
	}
	x := &traceStreamTracesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Trace_StreamTracesClient interface {
	Recv() (*StreamTracesResponse, error)
	grpc.ClientStream
}

type traceStreamTracesClient struct {
	grpc.ClientStream
}

func (x *traceStreamTracesClient) Recv() (*StreamTracesResponse, error) {
	m := new(StreamTracesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TraceServer is the server API for Trace service.
// All implementations must embed UnimplementedTraceServer
// for forward compatibility
type TraceServer interface {
	// Stream Compass traces from a specific environment.
	StreamTraces(*StreamTracesRequest, Trace_StreamTracesServer) error
	mustEmbedUnimplementedTraceServer()
}

// UnimplementedTraceServer must be embedded to have forward compatible implementations.
type UnimplementedTraceServer struct {
}

func (UnimplementedTraceServer) StreamTraces(*StreamTracesRequest, Trace_StreamTracesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamTraces not implemented")
}
func (UnimplementedTraceServer) mustEmbedUnimplementedTraceServer() {}

// UnsafeTraceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TraceServer will
// result in compilation errors.
type UnsafeTraceServer interface {
	mustEmbedUnimplementedTraceServer()
}

func RegisterTraceServer(s grpc.ServiceRegistrar, srv TraceServer) {
	s.RegisterService(&Trace_ServiceDesc, srv)
}

func _Trace_StreamTraces_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTracesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TraceServer).StreamTraces(m, &traceStreamTracesServer{stream})
}

type Trace_StreamTracesServer interface {
	Send(*StreamTracesResponse) error
	grpc.ServerStream
}

type traceStreamTracesServer struct {
	grpc.ServerStream
}

func (x *traceStreamTracesServer) Send(m *StreamTracesResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Trace_ServiceDesc is the grpc.ServiceDesc for Trace service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Trace_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "workflow.trace",
	HandlerType: (*TraceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTraces",
			Handler:       _Trace_StreamTraces_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "trace.proto",
}
