//* Service responsible for coordinating environment volumes

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: volume.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VolumeBackupStatus_Phase int32

const (
	VolumeBackupStatus_InProgress VolumeBackupStatus_Phase = 0 // Default value
	VolumeBackupStatus_Completed  VolumeBackupStatus_Phase = 1 // The backup completed
	VolumeBackupStatus_Failed     VolumeBackupStatus_Phase = 2 // The backup failed
	VolumeBackupStatus_Unknown    VolumeBackupStatus_Phase = 3 // Backup status is unknown
)

// Enum value maps for VolumeBackupStatus_Phase.
var (
	VolumeBackupStatus_Phase_name = map[int32]string{
		0: "InProgress",
		1: "Completed",
		2: "Failed",
		3: "Unknown",
	}
	VolumeBackupStatus_Phase_value = map[string]int32{
		"InProgress": 0,
		"Completed":  1,
		"Failed":     2,
		"Unknown":    3,
	}
)

func (x VolumeBackupStatus_Phase) Enum() *VolumeBackupStatus_Phase {
	p := new(VolumeBackupStatus_Phase)
	*p = x
	return p
}

func (x VolumeBackupStatus_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VolumeBackupStatus_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_volume_proto_enumTypes[0].Descriptor()
}

func (VolumeBackupStatus_Phase) Type() protoreflect.EnumType {
	return &file_volume_proto_enumTypes[0]
}

func (x VolumeBackupStatus_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VolumeBackupStatus_Phase.Descriptor instead.
func (VolumeBackupStatus_Phase) EnumDescriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{6, 0}
}

type VolumeRestoreStatus_Phase int32

const (
	VolumeRestoreStatus_InProgress VolumeRestoreStatus_Phase = 0 // Default value
	VolumeRestoreStatus_Completed  VolumeRestoreStatus_Phase = 1 // The backup completed
	VolumeRestoreStatus_Failed     VolumeRestoreStatus_Phase = 2 // The backup failed
	VolumeRestoreStatus_Unknown    VolumeRestoreStatus_Phase = 3 // Backup status is unknown
)

// Enum value maps for VolumeRestoreStatus_Phase.
var (
	VolumeRestoreStatus_Phase_name = map[int32]string{
		0: "InProgress",
		1: "Completed",
		2: "Failed",
		3: "Unknown",
	}
	VolumeRestoreStatus_Phase_value = map[string]int32{
		"InProgress": 0,
		"Completed":  1,
		"Failed":     2,
		"Unknown":    3,
	}
)

func (x VolumeRestoreStatus_Phase) Enum() *VolumeRestoreStatus_Phase {
	p := new(VolumeRestoreStatus_Phase)
	*p = x
	return p
}

func (x VolumeRestoreStatus_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VolumeRestoreStatus_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_volume_proto_enumTypes[1].Descriptor()
}

func (VolumeRestoreStatus_Phase) Type() protoreflect.EnumType {
	return &file_volume_proto_enumTypes[1]
}

func (x VolumeRestoreStatus_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VolumeRestoreStatus_Phase.Descriptor instead.
func (VolumeRestoreStatus_Phase) EnumDescriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{13, 0}
}

// *
// List volumes backups for an environment
type VolumeBackupListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Environment string `protobuf:"bytes,1,opt,name=Environment,proto3" json:"Environment,omitempty"` // Environment name
}

func (x *VolumeBackupListRequest) Reset() {
	*x = VolumeBackupListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volume_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeBackupListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeBackupListRequest) ProtoMessage() {}

func (x *VolumeBackupListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeBackupListRequest.ProtoReflect.Descriptor instead.
func (*VolumeBackupListRequest) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{0}
}

func (x *VolumeBackupListRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

// *
// Returns list of volume backups
type VolumeBackupListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*VolumeBackupStatus `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"` // List of volume backups
}

func (x *VolumeBackupListResponse) Reset() {
	*x = VolumeBackupListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volume_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeBackupListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeBackupListResponse) ProtoMessage() {}

func (x *VolumeBackupListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeBackupListResponse.ProtoReflect.Descriptor instead.
func (*VolumeBackupListResponse) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{1}
}

func (x *VolumeBackupListResponse) GetList() []*VolumeBackupStatus {
	if x != nil {
		return x.List
	}
	return nil
}

// *
// Create a volume backup
type VolumeBackupCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Environment string `protobuf:"bytes,1,opt,name=Environment,proto3" json:"Environment,omitempty"` // Environment name
	VolumeName  string `protobuf:"bytes,2,opt,name=VolumeName,proto3" json:"VolumeName,omitempty"`   // Volume name
}

func (x *VolumeBackupCreateRequest) Reset() {
	*x = VolumeBackupCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volume_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeBackupCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeBackupCreateRequest) ProtoMessage() {}

func (x *VolumeBackupCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeBackupCreateRequest.ProtoReflect.Descriptor instead.
func (*VolumeBackupCreateRequest) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{2}
}

func (x *VolumeBackupCreateRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *VolumeBackupCreateRequest) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

// *
// Returns a volume backup ID
type VolumeBackupCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *VolumeBackupCreateResponse) Reset() {
	*x = VolumeBackupCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volume_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeBackupCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeBackupCreateResponse) ProtoMessage() {}

func (x *VolumeBackupCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeBackupCreateResponse.ProtoReflect.Descriptor instead.
func (*VolumeBackupCreateResponse) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{3}
}

func (x *VolumeBackupCreateResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

// *
// Get the latest volume backup information
type VolumeBackupGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"` // ID of the backup
}

func (x *VolumeBackupGetRequest) Reset() {
	*x = VolumeBackupGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volume_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeBackupGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeBackupGetRequest) ProtoMessage() {}

func (x *VolumeBackupGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeBackupGetRequest.ProtoReflect.Descriptor instead.
func (*VolumeBackupGetRequest) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{4}
}

func (x *VolumeBackupGetRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

// *
// Returns the latest backup information
type VolumeBackupGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumeBackup *VolumeBackupStatus `protobuf:"bytes,1,opt,name=VolumeBackup,proto3" json:"VolumeBackup,omitempty"` // Backup status
}

func (x *VolumeBackupGetResponse) Reset() {
	*x = VolumeBackupGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volume_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeBackupGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeBackupGetResponse) ProtoMessage() {}

func (x *VolumeBackupGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeBackupGetResponse.ProtoReflect.Descriptor instead.
func (*VolumeBackupGetResponse) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{5}
}

func (x *VolumeBackupGetResponse) GetVolumeBackup() *VolumeBackupStatus {
	if x != nil {
		return x.VolumeBackup
	}
	return nil
}

// *
// Backup status information
type VolumeBackupStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string                   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`                                           // Name of the volume backup
	Phase          VolumeBackupStatus_Phase `protobuf:"varint,2,opt,name=phase,proto3,enum=workflow.VolumeBackupStatus_Phase" json:"phase,omitempty"` // Phase that the volume backup is in
	StartTime      string                   `protobuf:"bytes,3,opt,name=StartTime,proto3" json:"StartTime,omitempty"`                                 // When the volume backup started
	CompletionTime string                   `protobuf:"bytes,4,opt,name=CompletionTime,proto3" json:"CompletionTime,omitempty"`                       // When the volume backup completed
	Duration       string                   `protobuf:"bytes,5,opt,name=Duration,proto3" json:"Duration,omitempty"`                                   // How long the volume backup took to finish
	Volume         string                   `protobuf:"bytes,6,opt,name=Volume,proto3" json:"Volume,omitempty"`                                       // Volumes associated with backup
	BackupID       string                   `protobuf:"bytes,7,opt,name=BackupID,proto3" json:"BackupID,omitempty"`                                   // ID of the volume backup
}

func (x *VolumeBackupStatus) Reset() {
	*x = VolumeBackupStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volume_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeBackupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeBackupStatus) ProtoMessage() {}

func (x *VolumeBackupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeBackupStatus.ProtoReflect.Descriptor instead.
func (*VolumeBackupStatus) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{6}
}

func (x *VolumeBackupStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeBackupStatus) GetPhase() VolumeBackupStatus_Phase {
	if x != nil {
		return x.Phase
	}
	return VolumeBackupStatus_InProgress
}

func (x *VolumeBackupStatus) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *VolumeBackupStatus) GetCompletionTime() string {
	if x != nil {
		return x.CompletionTime
	}
	return ""
}

func (x *VolumeBackupStatus) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *VolumeBackupStatus) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *VolumeBackupStatus) GetBackupID() string {
	if x != nil {
		return x.BackupID
	}
	return ""
}

// *
// List volume restores for an environment
type VolumeRestoreListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Environment string `protobuf:"bytes,1,opt,name=Environment,proto3" json:"Environment,omitempty"` // Environment name
}

func (x *VolumeRestoreListRequest) Reset() {
	*x = VolumeRestoreListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volume_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeRestoreListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeRestoreListRequest) ProtoMessage() {}

func (x *VolumeRestoreListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeRestoreListRequest.ProtoReflect.Descriptor instead.
func (*VolumeRestoreListRequest) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{7}
}

func (x *VolumeRestoreListRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

// *
// Returns a list of volume restores
type VolumeRestoreListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*VolumeRestoreStatus `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"` // Volume restores
}

func (x *VolumeRestoreListResponse) Reset() {
	*x = VolumeRestoreListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volume_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeRestoreListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeRestoreListResponse) ProtoMessage() {}

func (x *VolumeRestoreListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeRestoreListResponse.ProtoReflect.Descriptor instead.
func (*VolumeRestoreListResponse) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{8}
}

func (x *VolumeRestoreListResponse) GetList() []*VolumeRestoreStatus {
	if x != nil {
		return x.List
	}
	return nil
}

// *
// Create a volume restore
type VolumeRestoreCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Environment string `protobuf:"bytes,1,opt,name=Environment,proto3" json:"Environment,omitempty"` // Environment name
	Backup      string `protobuf:"bytes,2,opt,name=Backup,proto3" json:"Backup,omitempty"`           // Backup name
	VolumeName  string `protobuf:"bytes,3,opt,name=VolumeName,proto3" json:"VolumeName,omitempty"`   // Volume name
}

func (x *VolumeRestoreCreateRequest) Reset() {
	*x = VolumeRestoreCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volume_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeRestoreCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeRestoreCreateRequest) ProtoMessage() {}

func (x *VolumeRestoreCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeRestoreCreateRequest.ProtoReflect.Descriptor instead.
func (*VolumeRestoreCreateRequest) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{9}
}

func (x *VolumeRestoreCreateRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *VolumeRestoreCreateRequest) GetBackup() string {
	if x != nil {
		return x.Backup
	}
	return ""
}

func (x *VolumeRestoreCreateRequest) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

// *
// Returns the ID of the created restore
type VolumeRestoreCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *VolumeRestoreCreateResponse) Reset() {
	*x = VolumeRestoreCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volume_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeRestoreCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeRestoreCreateResponse) ProtoMessage() {}

func (x *VolumeRestoreCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeRestoreCreateResponse.ProtoReflect.Descriptor instead.
func (*VolumeRestoreCreateResponse) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{10}
}

func (x *VolumeRestoreCreateResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

// *
// Get the latest backup information
type VolumeRestoreGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"` // ID of the restore
}

func (x *VolumeRestoreGetRequest) Reset() {
	*x = VolumeRestoreGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volume_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeRestoreGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeRestoreGetRequest) ProtoMessage() {}

func (x *VolumeRestoreGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeRestoreGetRequest.ProtoReflect.Descriptor instead.
func (*VolumeRestoreGetRequest) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{11}
}

func (x *VolumeRestoreGetRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

// *
// Returns the volume restore status
type VolumeRestoreGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumeRestore *VolumeRestoreStatus `protobuf:"bytes,1,opt,name=VolumeRestore,proto3" json:"VolumeRestore,omitempty"` // Restore status
}

func (x *VolumeRestoreGetResponse) Reset() {
	*x = VolumeRestoreGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volume_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeRestoreGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeRestoreGetResponse) ProtoMessage() {}

func (x *VolumeRestoreGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeRestoreGetResponse.ProtoReflect.Descriptor instead.
func (*VolumeRestoreGetResponse) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{12}
}

func (x *VolumeRestoreGetResponse) GetVolumeRestore() *VolumeRestoreStatus {
	if x != nil {
		return x.VolumeRestore
	}
	return nil
}

// *
// Volume restore status information
type VolumeRestoreStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string                    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`                                            // Name of the restore
	RestoreID      string                    `protobuf:"bytes,2,opt,name=RestoreID,proto3" json:"RestoreID,omitempty"`                                  // ID used for volume restore
	Phase          VolumeRestoreStatus_Phase `protobuf:"varint,3,opt,name=phase,proto3,enum=workflow.VolumeRestoreStatus_Phase" json:"phase,omitempty"` // Phase that the volume backup is in
	StartTime      string                    `protobuf:"bytes,4,opt,name=StartTime,proto3" json:"StartTime,omitempty"`                                  // When the volume backup started
	CompletionTime string                    `protobuf:"bytes,5,opt,name=CompletionTime,proto3" json:"CompletionTime,omitempty"`                        // When the volume backup completed
	Duration       string                    `protobuf:"bytes,6,opt,name=Duration,proto3" json:"Duration,omitempty"`                                    // How long the volume backup took to finish
	VolumeName     string                    `protobuf:"bytes,7,opt,name=VolumeName,proto3" json:"VolumeName,omitempty"`                                // Name of the volume
	BackupID       string                    `protobuf:"bytes,8,opt,name=BackupID,proto3" json:"BackupID,omitempty"`                                    // ID of the backup used
}

func (x *VolumeRestoreStatus) Reset() {
	*x = VolumeRestoreStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volume_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeRestoreStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeRestoreStatus) ProtoMessage() {}

func (x *VolumeRestoreStatus) ProtoReflect() protoreflect.Message {
	mi := &file_volume_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeRestoreStatus.ProtoReflect.Descriptor instead.
func (*VolumeRestoreStatus) Descriptor() ([]byte, []int) {
	return file_volume_proto_rawDescGZIP(), []int{13}
}

func (x *VolumeRestoreStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VolumeRestoreStatus) GetRestoreID() string {
	if x != nil {
		return x.RestoreID
	}
	return ""
}

func (x *VolumeRestoreStatus) GetPhase() VolumeRestoreStatus_Phase {
	if x != nil {
		return x.Phase
	}
	return VolumeRestoreStatus_InProgress
}

func (x *VolumeRestoreStatus) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *VolumeRestoreStatus) GetCompletionTime() string {
	if x != nil {
		return x.CompletionTime
	}
	return ""
}

func (x *VolumeRestoreStatus) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *VolumeRestoreStatus) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *VolumeRestoreStatus) GetBackupID() string {
	if x != nil {
		return x.BackupID
	}
	return ""
}

var File_volume_proto protoreflect.FileDescriptor

var file_volume_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x22, 0x3b, 0x0a, 0x17, 0x56, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x4c, 0x0a, 0x18, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x30, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x5d, 0x0a, 0x19, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x2c, 0x0a, 0x1a, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x22, 0x28, 0x0a, 0x16, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x5b, 0x0a, 0x17, 0x56, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x61, 0x63,
	0x6b, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x56, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x22, 0xb9, 0x02, 0x0a, 0x12, 0x56, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x38, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x22, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e,
	0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x49, 0x44, 0x22, 0x3f, 0x0a, 0x05, 0x50, 0x68, 0x61, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x49,
	0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x10, 0x03, 0x22, 0x3c, 0x0a, 0x18, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x22, 0x4e, 0x0a, 0x19, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x04, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x76, 0x0a, 0x1a, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x1b, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x29, 0x0a, 0x17, 0x56, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x49, 0x44, 0x22, 0x5f, 0x0a, 0x18, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x43, 0x0a, 0x0d, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0d, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x22, 0xe1, 0x02, 0x0a, 0x13, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x44, 0x12, 0x39,
	0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x50, 0x68, 0x61,
	0x73, 0x65, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42,
	0x61, 0x63, 0x6b, 0x75, 0x70, 0x49, 0x44, 0x22, 0x3f, 0x0a, 0x05, 0x50, 0x68, 0x61, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x03, 0x32, 0xa1, 0x04, 0x0a, 0x06, 0x76, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x12, 0x55, 0x0a, 0x0a, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x21, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x6f, 0x6c,
	0x75, 0x6d, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e,
	0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0b, 0x52, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x0c, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e,
	0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75,
	0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x52, 0x0a, 0x09, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x47, 0x65, 0x74, 0x12, 0x20,
	0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x47, 0x65, 0x74, 0x12, 0x21, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x2e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_volume_proto_rawDescOnce sync.Once
	file_volume_proto_rawDescData = file_volume_proto_rawDesc
)

func file_volume_proto_rawDescGZIP() []byte {
	file_volume_proto_rawDescOnce.Do(func() {
		file_volume_proto_rawDescData = protoimpl.X.CompressGZIP(file_volume_proto_rawDescData)
	})
	return file_volume_proto_rawDescData
}

var file_volume_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_volume_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_volume_proto_goTypes = []interface{}{
	(VolumeBackupStatus_Phase)(0),       // 0: workflow.VolumeBackupStatus.Phase
	(VolumeRestoreStatus_Phase)(0),      // 1: workflow.VolumeRestoreStatus.Phase
	(*VolumeBackupListRequest)(nil),     // 2: workflow.VolumeBackupListRequest
	(*VolumeBackupListResponse)(nil),    // 3: workflow.VolumeBackupListResponse
	(*VolumeBackupCreateRequest)(nil),   // 4: workflow.VolumeBackupCreateRequest
	(*VolumeBackupCreateResponse)(nil),  // 5: workflow.VolumeBackupCreateResponse
	(*VolumeBackupGetRequest)(nil),      // 6: workflow.VolumeBackupGetRequest
	(*VolumeBackupGetResponse)(nil),     // 7: workflow.VolumeBackupGetResponse
	(*VolumeBackupStatus)(nil),          // 8: workflow.VolumeBackupStatus
	(*VolumeRestoreListRequest)(nil),    // 9: workflow.VolumeRestoreListRequest
	(*VolumeRestoreListResponse)(nil),   // 10: workflow.VolumeRestoreListResponse
	(*VolumeRestoreCreateRequest)(nil),  // 11: workflow.VolumeRestoreCreateRequest
	(*VolumeRestoreCreateResponse)(nil), // 12: workflow.VolumeRestoreCreateResponse
	(*VolumeRestoreGetRequest)(nil),     // 13: workflow.VolumeRestoreGetRequest
	(*VolumeRestoreGetResponse)(nil),    // 14: workflow.VolumeRestoreGetResponse
	(*VolumeRestoreStatus)(nil),         // 15: workflow.VolumeRestoreStatus
}
var file_volume_proto_depIdxs = []int32{
	8,  // 0: workflow.VolumeBackupListResponse.List:type_name -> workflow.VolumeBackupStatus
	8,  // 1: workflow.VolumeBackupGetResponse.VolumeBackup:type_name -> workflow.VolumeBackupStatus
	0,  // 2: workflow.VolumeBackupStatus.phase:type_name -> workflow.VolumeBackupStatus.Phase
	15, // 3: workflow.VolumeRestoreListResponse.List:type_name -> workflow.VolumeRestoreStatus
	15, // 4: workflow.VolumeRestoreGetResponse.VolumeRestore:type_name -> workflow.VolumeRestoreStatus
	1,  // 5: workflow.VolumeRestoreStatus.phase:type_name -> workflow.VolumeRestoreStatus.Phase
	2,  // 6: workflow.volume.BackupList:input_type -> workflow.VolumeBackupListRequest
	9,  // 7: workflow.volume.RestoreList:input_type -> workflow.VolumeRestoreListRequest
	4,  // 8: workflow.volume.BackupCreate:input_type -> workflow.VolumeBackupCreateRequest
	6,  // 9: workflow.volume.BackupGet:input_type -> workflow.VolumeBackupGetRequest
	11, // 10: workflow.volume.RestoreCreate:input_type -> workflow.VolumeRestoreCreateRequest
	13, // 11: workflow.volume.RestoreGet:input_type -> workflow.VolumeRestoreGetRequest
	3,  // 12: workflow.volume.BackupList:output_type -> workflow.VolumeBackupListResponse
	10, // 13: workflow.volume.RestoreList:output_type -> workflow.VolumeRestoreListResponse
	5,  // 14: workflow.volume.BackupCreate:output_type -> workflow.VolumeBackupCreateResponse
	7,  // 15: workflow.volume.BackupGet:output_type -> workflow.VolumeBackupGetResponse
	12, // 16: workflow.volume.RestoreCreate:output_type -> workflow.VolumeRestoreCreateResponse
	14, // 17: workflow.volume.RestoreGet:output_type -> workflow.VolumeRestoreGetResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_volume_proto_init() }
func file_volume_proto_init() {
	if File_volume_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_volume_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeBackupListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volume_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeBackupListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volume_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeBackupCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volume_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeBackupCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volume_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeBackupGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volume_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeBackupGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volume_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeBackupStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volume_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeRestoreListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volume_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeRestoreListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volume_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeRestoreCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volume_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeRestoreCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volume_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeRestoreGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volume_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeRestoreGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volume_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeRestoreStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_volume_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_volume_proto_goTypes,
		DependencyIndexes: file_volume_proto_depIdxs,
		EnumInfos:         file_volume_proto_enumTypes,
		MessageInfos:      file_volume_proto_msgTypes,
	}.Build()
	File_volume_proto = out.File
	file_volume_proto_rawDesc = nil
	file_volume_proto_goTypes = nil
	file_volume_proto_depIdxs = nil
}
