name: 📋 Lint

on:
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]

jobs:
  lint:
    name: 📋 Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v6

      - name: 📦 Install Mise
        uses: jdx/mise-action@v4

      - name: 🧪 Lint
        run: mise run lint
